version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - "./taxi_fare/test.csv:/taxi_fare/test.csv"
      - "./taxi_fare/train.csv:/taxi_fare/train.csv"
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_blocksize=67108864  # Block size 64 MB
    env_file:
      - ./hadoop.env
    networks:
      - network
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 2G

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - network
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 4G

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    hostname: spark-master
    depends_on:
      - namenode
      - datanode1
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - hadoop.env
    environment:
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    volumes:
      - "./app/app.py:/opt/bitnami/spark/app.py"
      - "./requirements.txt:/requirements.txt"
      - "./images:/opt/bitnami/spark/images"
    networks:
      - network
    deploy:
      resources:
        limits:
          memory: 7G

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./requirements.txt:/requirements.txt"
    env_file:
      hadoop.env
    networks:
      - network

  
volumes:
  hadoop_namenode:
  hadoop_datanode1:

networks:
  network:
    driver: bridge
    name: network
